"""Owned strikeout projection served from MLB StatsAPI only — no external
model service. Poisson GLM; constants in kmodel_params.py (auto-generated by
calibration/train_kmodel.py from 9,670 pre-May starts; MAE 1.78 K, bias
-0.03 on 1,893 held-out starts).

Used by feed.lambdas_for as the LAST link in the projection chain
(slate -> per-pitcher predict -> THIS), so a dead upstream service can no
longer take the whole app down (2026-07-13: mlb-edge returned an empty
slate, then HTTP 500 — no board was captured all day).

Features are built live per pitcher, all free StatsAPI:
  - rolling K/BF (3/10) + career prior, shrunk 150 pseudo-BF (gameLog)
  - rolling BF over last 3 starts (the leash)
  - opponent team season K/PA (shrunk); lineup-level once confirmed
  - home/away, rest days (schedule + probables), park factor (fitted table)
Any missing piece degrades to the training mean of that feature — a real
number always comes back for a probable starter with >= 2 prior starts.
"""
from __future__ import annotations

import hashlib
import json
import math
import sys
import urllib.parse
import urllib.request
from datetime import date as _date

from feed import norm
from kmodel_params import COEF, FEATURES, INTERCEPT, MEAN, PARKS, SD

try:                                   # emitted by train_kmodel.py from v2 on
    from kmodel_params import VERSION
except ImportError:
    # Params files generated before versioning still need a stable identity, and
    # a content hash gives one without a retrain: same coefficients -> same
    # string, any retrain -> a different one. That is the whole contract
    # mu_version has to satisfy.
    VERSION = "sha-" + hashlib.md5(
        repr((FEATURES, MEAN, SD, COEF, INTERCEPT)).encode()).hexdigest()[:8]

_LG_KBF = 0.22
_PRIOR_BF = 150.0


def _warn(what: str, exc: BaseException, schema: bool = False) -> None:
    """One line to stderr; the hourly cron log keeps it (deploy/fantasy.logrotate).

    Every degradation in this module is silent by design — a missing feature
    falls back to its training mean and a real number still comes back. That
    keeps the board alive when StatsAPI wobbles, but it also means a PERMANENT
    break (an endpoint renamed, a field retyped) looks exactly like a slow
    afternoon: projections quietly built on training means for every pitcher,
    with nothing anywhere saying so.

    So the fallback stays, and the failure gets said out loud. `schema=True`
    marks the kind that will not fix itself — a network blip repeats a few times
    an hour, a schema break repeats forever and needs a human.
    """
    kind = "SCHEMA" if schema else "fetch"
    print(f"kmodel: {kind} {what}: {type(exc).__name__}: {exc}", file=sys.stderr)


def _expect(payload: dict, key: str, what: str) -> bool:
    """True if `key` is present. Warns and returns False if the shape changed.

    The parsing below is written in defensive .get(x, default) chains, so a
    renamed endpoint or retyped field raises NOTHING — it returns an empty
    result that is indistinguishable from a quiet news day. That is why the
    except-clauses alone could never surface a schema break: there was no
    exception to catch. Asserting the top-level key we depend on separates
    "no data" (legitimate: empty list, no games yet) from "not the response we
    were promised" (a break that will never fix itself).
    """
    if isinstance(payload, dict) and key in payload:
        return True
    got = sorted(payload)[:6] if isinstance(payload, dict) else type(payload).__name__
    print(f"kmodel: SCHEMA {what}: no {key!r} in response (got {got})",
          file=sys.stderr)
    return False


def _get(url):
    with urllib.request.urlopen(url, timeout=45) as r:
        return json.load(r)


_sched_cache: dict[str, dict] = {}
_teamk_cache: dict[tuple[int, int], float] = {}
_log_cache: dict[int, list[dict]] = {}
_pid_cache: dict[str, int | None] = {}


def _player_id(name: str) -> int | None:
    key = norm(name)
    if key in _pid_cache:
        return _pid_cache[key]
    try:
        s = _get("https://statsapi.mlb.com/api/v1/people/search?names="
                 + urllib.parse.quote(name))
    except Exception as e:
        _warn(f"player search {name!r}", e)
        _pid_cache[key] = None
        return None
    if not _expect(s, "people", f"people/search for {name!r}"):
        _pid_cache[key] = None
        return None
    try:
        ppl = s.get("people", [])
        pid = next((p["id"] for p in ppl if norm(p.get("fullName", "")) == key),
                   ppl[0]["id"] if ppl else None)
    except Exception as e:
        _warn(f"people/search shape for {name!r}", e, schema=True)
        pid = None
    _pid_cache[key] = pid
    return pid


def _schedule(date: str) -> dict:
    """norm(probable) -> {team_id, opp_id, home, venue_abbr}."""
    if date in _sched_cache:
        return _sched_cache[date]
    out: dict[str, dict] = {}
    try:
        s = _get("https://statsapi.mlb.com/api/v1/schedule?sportId=1&date="
                 + date + "&hydrate=probablePitcher,team")
    except Exception as e:
        _warn(f"schedule {date}", e)
        _sched_cache[date] = out
        return out
    if not _expect(s, "dates", f"schedule {date}"):
        _sched_cache[date] = out
        return out
    try:
        for d in s.get("dates", []):
            for g in d.get("games", []):
                home, away = g["teams"]["home"], g["teams"]["away"]
                habbr = home["team"].get("abbreviation") or home["team"]["name"]
                for side, other, is_home in ((home, away, True), (away, home, False)):
                    pp = side.get("probablePitcher") or {}
                    if pp.get("fullName"):
                        out[norm(pp["fullName"])] = {
                            "team": side["team"]["id"],
                            "opp": other["team"]["id"],
                            "home": is_home, "venue": habbr}
    except Exception as e:
        # Partial `out` is kept deliberately: the pitchers parsed before the
        # break are still correct, and every one missing degrades to feature
        # means rather than vanishing from the board.
        _warn(f"schedule shape for {date} ({len(out)} parsed before break)",
              e, schema=True)
    _sched_cache[date] = out
    return out


def _team_k_pa(team_id: int, season: int) -> float | None:
    ck = (team_id, season)
    if ck in _teamk_cache:
        return _teamk_cache[ck]
    try:
        st = _get(f"https://statsapi.mlb.com/api/v1/teams/{team_id}/stats"
                  f"?season={season}&group=hitting&stats=season")
    except Exception as e:
        _warn(f"team {team_id} hitting stats", e)
        _teamk_cache[ck] = None
        return None
    if not _expect(st, "stats", f"team {team_id} hitting stats"):
        _teamk_cache[ck] = None
        return None
    try:
        # `or [{}]`, not a .get default: the key EXISTS and is an empty list for
        # a team with no games logged yet. A default only fires on a missing key.
        s = (st.get("stats") or [{}])[0]
        s = (s.get("splits") or [{}])[0].get("stat", {})
        k = float(s.get("strikeOuts", 0) or 0)
        pa = float(s.get("plateAppearances", 0) or 0)
        v = (k + 50 * _LG_KBF) / (pa + 50) if pa else None
    except Exception as e:
        _warn(f"team stats shape for {team_id}", e, schema=True)
        v = None
    _teamk_cache[ck] = v
    return v


def _starts(pid: int, season: int) -> list[dict]:
    """This season's starts (K/BF/pitches/date), oldest first, from gameLog."""
    if pid in _log_cache:
        return _log_cache[pid]
    rows = []
    try:
        st = _get(f"https://statsapi.mlb.com/api/v1/people/{pid}/stats"
                  f"?stats=gameLog&group=pitching&season={season}")
    except Exception as e:
        _warn(f"gameLog for pitcher {pid}", e)
        _log_cache[pid] = rows
        return rows
    if not _expect(st, "stats", f"gameLog for pitcher {pid}"):
        _log_cache[pid] = rows
        return rows
    try:
        for spl in (st.get("stats") or [{}])[0].get("splits") or []:
            s = spl.get("stat", {})
            if int(s.get("gamesStarted", 0) or 0) < 1:
                continue
            rows.append({"date": spl.get("date"),
                         "K": float(s.get("strikeOuts", 0) or 0),
                         "BF": float(s.get("battersFaced", 0) or 0)})
        rows.sort(key=lambda r: r["date"] or "")
    except Exception as e:
        _warn(f"gameLog shape for pitcher {pid}", e, schema=True)
    _log_cache[pid] = rows
    return rows


def _kbf(h: list[dict], last: int | None) -> float:
    hh = h if last is None else h[-last:]
    k = sum(x["K"] for x in hh)
    bf = sum(x["BF"] for x in hh)
    return (k + _PRIOR_BF * _LG_KBF) / (bf + _PRIOR_BF)


def project_detail(name: str, date: str) -> dict | None:
    """Projection plus the exact inputs it was computed from, or None if the
    starter has fewer than 2 prior starts this season (no form to project from).

    `imputed` names the features that fell back to the training mean. That
    substitution is silent inside the GLM — a pitcher whose opponent lookup
    failed scores as a league-average matchup and looks like a normal
    projection. Surfacing it here is what lets the feature sidecar detect
    serving-vs-training drift instead of it hiding in the residuals.
    """
    pid = _player_id(name)
    if pid is None:
        return None
    season = int(date[:4])
    h = [s for s in _starts(pid, season) if (s["date"] or "") < date]
    if len(h) < 2:
        return None
    sched = _schedule(date).get(norm(name), {})
    opp_k = _team_k_pa(sched["opp"], season) if sched.get("opp") else None
    rest = None
    if h[-1]["date"]:
        rest = (_date.fromisoformat(date) - _date.fromisoformat(h[-1]["date"])).days
        rest = float(min(max(rest, 3), 12))
    feats = {
        "roll_kbf_3": _kbf(h, 3), "roll_kbf_10": _kbf(h, 10),
        "prior_kbf": _kbf(h, None),
        "roll_bf_3": sum(x["BF"] for x in h[-3:]) / min(len(h), 3),
        "opp_k_pct": opp_k, "is_home": 1.0 if sched.get("home") else 0.0,
        "rest_days": rest, "park_k": PARKS.get(sched.get("venue"), 1.0),
    }
    z = INTERCEPT
    imputed = []
    for f, m, s, c in zip(FEATURES, MEAN, SD, COEF):
        x = feats.get(f)
        if x is None:
            x = m                      # missing feature -> training mean
            imputed.append(f)
        z += c * (x - m) / s
    return {"mu": math.exp(z), "features": feats, "imputed": imputed,
            "pid": pid, "venue": sched.get("venue"), "team": sched.get("team"),
            "opp": sched.get("opp"), "version": VERSION}


def project(name: str, date: str) -> float | None:
    """Model strikeout projection for a probable starter, or None."""
    d = project_detail(name, date)
    return None if d is None else d["mu"]
